/**
 * Starting catalogue for Evora Home.
 *
 * This is scaffolding, not the deliverable. Names, references, prices and
 * dimensions are plausible for an Algerian furniture shop in this price band,
 * but the client supplies the real ones before launch.
 *
 * IMAGE CONVENTION
 * Every image path is `/products/<slug>-NN.jpg`, served from the client's
 * public directory. Dropping the client's real photos into
 * `client/public/products/` using that naming replaces the placeholders with
 * no code change. Images are displayed in a fixed 4:5 crop with object-cover,
 * so any aspect ratio is safe; portrait shots simply lose the least.
 */

const COULEURS = {
  beigeSable: { nom: 'Beige sable', hex: '#D8CDB8' },
  grisPerle: { nom: 'Gris perle', hex: '#B9B7B0' },
  tauperFonce: { nom: 'Taupe foncé', hex: '#7A6E60' },
  vertOlive: { nom: 'Vert olive', hex: '#5A6350' },
  bleuNuit: { nom: 'Bleu nuit', hex: '#2E3A4A' },
  creme: { nom: 'Crème', hex: '#EDE5D6' },
  terracotta: { nom: 'Terracotta', hex: '#A9614A' },
  noyer: { nom: 'Noyer', hex: '#5C4433' },
  chene: { nom: 'Chêne clair', hex: '#C4A882' },
  anthracite: { nom: 'Anthracite', hex: '#3A3A3C' },
  blancCasse: { nom: 'Blanc cassé', hex: '#EFEBE3' },
  rouille: { nom: 'Rouille', hex: '#96502F' },
};

const c = (...keys) => keys.map((k) => COULEURS[k]);

export const CATEGORIES = [
  {
    nom: 'Salons',
    slug: 'salons',
    ordre: 1,
    description:
      "Canapés d'angle, ensembles trois pièces et fauteuils. Assises en tissu ou en velours, structures en bois massif.",
    image: '/products/categories/salons.jpg',
  },
  {
    nom: 'Chambres',
    slug: 'chambres',
    ordre: 2,
    description:
      'Lits, armoires, commodes et chevets. Ensembles complets ou pièces séparées, en placage ou en bois massif.',
    image: '/products/categories/chambres.jpg',
  },
  {
    nom: 'Tables & Chaises',
    slug: 'tables-et-chaises',
    ordre: 3,
    description:
      'Tables à manger fixes ou extensibles, tables basses et chaises. Plateaux en bois, en verre trempé et en marbre.',
    image: '/products/categories/tables-et-chaises.jpg',
  },
  {
    nom: 'Meubles TV',
    slug: 'meubles-tv',
    ordre: 4,
    description: 'Bancs TV et ensembles muraux, avec rangement fermé et passage de câbles.',
    image: '/products/categories/meubles-tv.jpg',
  },
  {
    nom: 'Consoles & Miroirs',
    slug: 'consoles-et-miroirs',
    ordre: 5,
    description: "Consoles d'entrée, coiffeuses et miroirs. Pour les entrées et les couloirs.",
    image: '/products/categories/consoles-et-miroirs.jpg',
  },
  {
    nom: 'Salon de Jardin',
    slug: 'salon-de-jardin',
    ordre: 6,
    description:
      'Ensembles de terrasse et de jardin en résine tressée et en aluminium, avec coussins déhoussables.',
    image: '/products/categories/salon-de-jardin.jpg',
  },
  {
    nom: 'Décoration',
    slug: 'decoration',
    ordre: 7,
    description: 'Tapis, luminaires, vases et objets. Les finitions qui terminent une pièce.',
    image: '/products/categories/decoration.jpg',
  },
];

/**
 * `images` is generated from the slug below, so entries here only declare how
 * many photos the product has. Products with a single image are included on
 * purpose: the gallery has to hold up without a thumbnail strip.
 */
export const PRODUITS = [
  // ── Salons ─────────────────────────────────────────────────────────────────
  {
    ref: 'LA CONNER',
    nom: "Canapé d'angle La Conner",
    categorie: 'salons',
    prix: 289000,
    nbImages: 4,
    description:
      "Angle réversible six places, assise profonde et dossier ferme. Le tissu bouclé est déhoussable sur les coussins d'assise. Structure en hêtre massif, suspension par sangles croisées.",
    dimensions: { largeur: 310, profondeur: 190, hauteur: 85 },
    materiaux: ['Tissu bouclé', 'Bois massif', 'Mousse haute densité'],
    couleurs: c('beigeSable', 'grisPerle', 'vertOlive'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
    isFeatured: true,
    isNouveau: true,
  },
  {
    ref: 'MONTEREY',
    nom: 'Ensemble salon Monterey',
    categorie: 'salons',
    prix: 345000,
    ancienPrix: 398000,
    nbImages: 3,
    description:
      "Trois pièces : un canapé trois places, un deux places et un fauteuil. Piètement en bois apparent, accoudoirs larges. Livré monté.",
    dimensions: { largeur: 220, profondeur: 95, hauteur: 88 },
    materiaux: ['Velours', 'Bois massif', 'Métal'],
    couleurs: c('bleuNuit', 'tauperFonce', 'terracotta'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
    isFeatured: true,
  },
  {
    ref: 'ASILAH',
    nom: 'Canapé trois places Asilah',
    categorie: 'salons',
    prix: 178000,
    nbImages: 3,
    description:
      'Ligne droite et piètement fin. Assise en mousse haute densité, dossier à coussins amovibles. Convient aux salons de taille moyenne.',
    dimensions: { largeur: 210, profondeur: 92, hauteur: 84 },
    materiaux: ['Tissu', 'Bois massif'],
    couleurs: c('grisPerle', 'creme', 'vertOlive'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
  },
  {
    ref: 'BENSALEM',
    nom: 'Salon marocain Bensalem',
    categorie: 'salons',
    prix: 265000,
    nbImages: 4,
    description:
      "Banquettes sur trois côtés avec coffres de rangement sous l'assise. Sculpture sur bois traditionnelle, tissu au choix. Fabriqué sur mesure aux dimensions de la pièce.",
    dimensions: { largeur: 400, profondeur: 300, hauteur: 80 },
    materiaux: ['Bois massif', 'Tissu', 'Mousse haute densité'],
    couleurs: c('rouille', 'vertOlive', 'beigeSable'),
    disponibilite: 'SUR_COMMANDE',
    delaiLivraison: '3 à 4 semaines',
  },
  {
    ref: 'CADIZ',
    nom: 'Canapé convertible Cadiz',
    categorie: 'salons',
    prix: 156000,
    nbImages: 2,
    description:
      'Couchage deux places par dépliage rapide, coffre de rangement pour la literie. Mécanisme métallique testé sur cycles.',
    dimensions: { largeur: 200, profondeur: 95, hauteur: 86 },
    materiaux: ['Tissu', 'Métal', 'MDF'],
    couleurs: c('anthracite', 'grisPerle'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
  },
  {
    ref: 'ORAN 7P',
    nom: 'Fauteuil Oran',
    categorie: 'salons',
    prix: 68000,
    nbImages: 2,
    description:
      "Fauteuil d'appoint à dossier haut, piètement en bois tourné. Se marie avec les ensembles Monterey et Asilah.",
    dimensions: { largeur: 78, profondeur: 82, hauteur: 98 },
    materiaux: ['Velours', 'Bois massif'],
    couleurs: c('bleuNuit', 'terracotta', 'vertOlive'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'TIPAZA',
    nom: "Canapé d'angle Tipaza",
    categorie: 'salons',
    prix: 232000,
    nbImages: 3,
    description:
      'Angle cinq places avec méridienne à gauche ou à droite, à préciser à la commande. Coussins de dossier garnis en fibre siliconée.',
    dimensions: { largeur: 280, profondeur: 170, hauteur: 82 },
    materiaux: ['Tissu', 'Bois massif', 'Mousse haute densité'],
    couleurs: c('beigeSable', 'tauperFonce', 'anthracite'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
    isFeatured: true,
  },
  {
    ref: 'SEVILLE',
    nom: 'Méridienne Seville',
    categorie: 'salons',
    prix: 94000,
    nbImages: 2,
    description: "Méridienne d'appoint à accoudoir unique. Se place en bout de canapé ou seule sous une fenêtre.",
    dimensions: { largeur: 165, profondeur: 78, hauteur: 80 },
    materiaux: ['Tissu bouclé', 'Bois massif'],
    couleurs: c('creme', 'grisPerle'),
    disponibilite: 'RUPTURE',
    delaiLivraison: '5 à 8 jours',
  },

  // ── Chambres ───────────────────────────────────────────────────────────────
  {
    ref: 'ALMERIA',
    nom: 'Chambre complète Almeria',
    categorie: 'chambres',
    prix: 385000,
    nbImages: 4,
    description:
      "Lit 160x200 avec tête de lit capitonnée, armoire quatre portes, commode et deux chevets. Placage noyer et poignées en métal brossé. Sommier inclus, matelas non inclus.",
    dimensions: { largeur: 250, profondeur: 220, hauteur: 220 },
    materiaux: ['MDF', 'Placage bois', 'Métal', 'Tissu'],
    couleurs: c('noyer', 'blancCasse'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '7 à 10 jours',
    isFeatured: true,
  },
  {
    ref: 'NERJA',
    nom: 'Lit Nerja 180x200',
    categorie: 'chambres',
    prix: 168000,
    nbImages: 3,
    description:
      'Lit king size à tête de lit haute et capitonnage vertical. Cadre sur pieds, sommier à lattes inclus. Matelas non inclus.',
    dimensions: { largeur: 196, profondeur: 216, hauteur: 130 },
    materiaux: ['Bois massif', 'Tissu', 'Mousse haute densité'],
    couleurs: c('beigeSable', 'grisPerle', 'vertOlive'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '7 à 10 jours',
    isNouveau: true,
  },
  {
    ref: 'CORDOBA',
    nom: 'Armoire Cordoba six portes',
    categorie: 'chambres',
    prix: 215000,
    nbImages: 2,
    description:
      "Armoire six portes avec penderie, étagères et deux tiroirs intérieurs. Miroir sur les deux portes centrales. Montage à domicile compris.",
    dimensions: { largeur: 270, profondeur: 60, hauteur: 225 },
    materiaux: ['MDF', 'Placage bois', 'Verre'],
    couleurs: c('noyer', 'blancCasse', 'chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '7 à 10 jours',
  },
  {
    ref: 'MERZOUGA',
    nom: 'Commode Merzouga',
    categorie: 'chambres',
    prix: 82000,
    nbImages: 2,
    description: 'Six tiroirs sur glissières métalliques à fermeture douce. Plateau en bois massif.',
    dimensions: { largeur: 120, profondeur: 45, hauteur: 85 },
    materiaux: ['Bois massif', 'MDF', 'Métal'],
    couleurs: c('chene', 'blancCasse'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
  },
  {
    ref: 'ESSAOUIRA',
    nom: 'Chambre enfant Essaouira',
    categorie: 'chambres',
    prix: 198000,
    nbImages: 3,
    description:
      "Lit 90x190, armoire deux portes, bureau et chevet. Angles arrondis sur toutes les pièces. Se décline en trois teintes.",
    dimensions: { largeur: 200, profondeur: 190, hauteur: 190 },
    materiaux: ['MDF', 'Bois massif'],
    couleurs: c('blancCasse', 'chene', 'grisPerle'),
    disponibilite: 'SUR_COMMANDE',
    delaiLivraison: '2 à 3 semaines',
  },
  {
    ref: 'TAMANRA',
    nom: 'Chevet Tamanra',
    categorie: 'chambres',
    prix: 24000,
    nbImages: 1,
    description: 'Deux tiroirs et une niche ouverte. Vendu à l\'unité.',
    dimensions: { largeur: 45, profondeur: 40, hauteur: 55 },
    materiaux: ['MDF', 'Placage bois'],
    couleurs: c('noyer', 'blancCasse', 'chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },

  // ── Tables & Chaises ───────────────────────────────────────────────────────
  {
    ref: 'VALENCIA',
    nom: 'Table à manger Valencia',
    categorie: 'tables-et-chaises',
    prix: 148000,
    nbImages: 3,
    description:
      'Table extensible de huit à dix couverts. Plateau en bois massif sur piètement central en métal laqué. Rallonge intégrée sous le plateau.',
    dimensions: { largeur: 180, profondeur: 100, hauteur: 76 },
    materiaux: ['Bois massif', 'Métal'],
    couleurs: c('noyer', 'chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '7 à 10 jours',
    isFeatured: true,
  },
  {
    ref: 'CARRARE',
    nom: 'Table à manger Carrare',
    categorie: 'tables-et-chaises',
    prix: 176000,
    nbImages: 2,
    description:
      'Plateau en marbre sur pied central en métal. Six couverts. Le veinage est propre à chaque plateau, aucune pièce n\'est identique.',
    dimensions: { largeur: 160, profondeur: 90, hauteur: 75 },
    materiaux: ['Marbre', 'Métal'],
    couleurs: c('blancCasse', 'anthracite'),
    disponibilite: 'SUR_COMMANDE',
    delaiLivraison: '3 à 4 semaines',
  },
  {
    ref: 'GRANADA',
    nom: 'Chaise Granada',
    categorie: 'tables-et-chaises',
    prix: 16500,
    nbImages: 2,
    description:
      'Assise garnie et dossier arrondi, piètement en bois massif. Vendue à l\'unité. Prévoir six à huit pièces pour une table Valencia.',
    dimensions: { largeur: 46, profondeur: 52, hauteur: 88 },
    materiaux: ['Tissu', 'Bois massif'],
    couleurs: c('beigeSable', 'vertOlive', 'bleuNuit', 'terracotta'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'MALAGA',
    nom: 'Table basse Malaga',
    categorie: 'tables-et-chaises',
    prix: 58000,
    nbImages: 2,
    description: 'Plateau en verre trempé sur structure en métal, tablette basse en bois. Angles adoucis.',
    dimensions: { largeur: 120, profondeur: 60, hauteur: 42 },
    materiaux: ['Verre trempé', 'Métal', 'Bois massif'],
    couleurs: c('anthracite', 'chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'TANGER',
    nom: 'Table basse Tanger, lot de deux',
    categorie: 'tables-et-chaises',
    prix: 46000,
    nbImages: 2,
    description: 'Deux tables gigognes rondes de hauteurs différentes. Se rangent l\'une sous l\'autre.',
    dimensions: { largeur: 70, profondeur: 70, hauteur: 45 },
    materiaux: ['Bois massif', 'Métal'],
    couleurs: c('noyer', 'chene', 'anthracite'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
    isNouveau: true,
  },
  {
    ref: 'RONDA',
    nom: 'Table de repas ronde Ronda',
    categorie: 'tables-et-chaises',
    prix: 98000,
    nbImages: 2,
    description: 'Quatre à six couverts sur un plateau rond et un pied tulipe. Convient aux pièces étroites.',
    dimensions: { largeur: 120, profondeur: 120, hauteur: 75 },
    materiaux: ['MDF', 'Placage bois', 'Métal'],
    couleurs: c('blancCasse', 'noyer'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '7 à 10 jours',
  },

  // ── Meubles TV ─────────────────────────────────────────────────────────────
  {
    ref: 'HORIZON',
    nom: 'Meuble TV Horizon',
    categorie: 'meubles-tv',
    prix: 78000,
    nbImages: 3,
    description:
      "Banc de 200 cm à deux portes battantes et une niche centrale ventilée. Passage de câbles à l'arrière. Pour écrans jusqu'à 75 pouces.",
    dimensions: { largeur: 200, profondeur: 40, hauteur: 45 },
    materiaux: ['MDF', 'Placage bois', 'Métal'],
    couleurs: c('noyer', 'anthracite', 'blancCasse'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
    isFeatured: true,
  },
  {
    ref: 'ANDALOUS',
    nom: 'Ensemble mural Andalous',
    categorie: 'meubles-tv',
    prix: 124000,
    nbImages: 3,
    description:
      "Composition murale avec banc TV, colonnes de rangement et étagères suspendues. Éclairage LED en option, à préciser à la commande.",
    dimensions: { largeur: 280, profondeur: 40, hauteur: 190 },
    materiaux: ['MDF', 'Verre trempé', 'Métal'],
    couleurs: c('blancCasse', 'anthracite'),
    disponibilite: 'SUR_COMMANDE',
    delaiLivraison: '2 à 3 semaines',
  },
  {
    ref: 'LOFT 40',
    nom: 'Meuble TV Loft',
    categorie: 'meubles-tv',
    prix: 42000,
    nbImages: 2,
    description: 'Banc compact à deux tiroirs sur piètement métallique fin. Pour écrans jusqu\'à 55 pouces.',
    dimensions: { largeur: 140, profondeur: 38, hauteur: 48 },
    materiaux: ['MDF', 'Métal'],
    couleurs: c('chene', 'anthracite'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'BEJAIA',
    nom: 'Meuble TV Bejaia',
    categorie: 'meubles-tv',
    prix: 64000,
    nbImages: 2,
    description: 'Quatre portes cannelées et un plateau en bois massif. Charnières à fermeture douce.',
    dimensions: { largeur: 180, profondeur: 42, hauteur: 52 },
    materiaux: ['Bois massif', 'MDF'],
    couleurs: c('chene', 'noyer'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
  },
  {
    ref: 'STUDIO 12',
    nom: 'Meuble TV suspendu Studio',
    categorie: 'meubles-tv',
    prix: 38000,
    nbImages: 1,
    description: 'Banc suspendu à deux abattants, fixations murales fournies. Libère le sol dans les petites pièces.',
    dimensions: { largeur: 150, profondeur: 35, hauteur: 30 },
    materiaux: ['MDF'],
    couleurs: c('blancCasse', 'anthracite', 'chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },

  // ── Consoles & Miroirs ─────────────────────────────────────────────────────
  {
    ref: 'ALHAMBRA',
    nom: "Console d'entrée Alhambra",
    categorie: 'consoles-et-miroirs',
    prix: 52000,
    nbImages: 2,
    description: 'Console étroite à deux tiroirs et tablette basse. Se pose dans un couloir sans le rétrécir.',
    dimensions: { largeur: 110, profondeur: 35, hauteur: 80 },
    materiaux: ['Bois massif', 'Métal'],
    couleurs: c('noyer', 'blancCasse'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'LUNA 90',
    nom: 'Miroir rond Luna',
    categorie: 'consoles-et-miroirs',
    prix: 28000,
    nbImages: 2,
    description: 'Miroir rond de 90 cm à cadre en métal fin. Fixations murales fournies.',
    dimensions: { largeur: 90, profondeur: 4, hauteur: 90 },
    materiaux: ['Verre', 'Métal'],
    couleurs: c('anthracite', 'chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
    isNouveau: true,
  },
  {
    ref: 'MIRAMAR',
    nom: 'Coiffeuse Miramar',
    categorie: 'consoles-et-miroirs',
    prix: 78000,
    nbImages: 3,
    description: 'Coiffeuse avec miroir, trois tiroirs et un tabouret assorti. Le miroir se démonte pour le transport.',
    dimensions: { largeur: 100, profondeur: 40, hauteur: 140 },
    materiaux: ['MDF', 'Verre', 'Tissu'],
    couleurs: c('blancCasse', 'noyer'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
  },
  {
    ref: 'PORTO',
    nom: 'Miroir Porto plein pied',
    categorie: 'consoles-et-miroirs',
    prix: 34000,
    nbImages: 1,
    description: "Miroir de 170 cm, à poser contre un mur ou à fixer. Cale antidérapante à la base.",
    dimensions: { largeur: 60, profondeur: 3, hauteur: 170 },
    materiaux: ['Verre', 'Métal'],
    couleurs: c('anthracite', 'chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'SAHEL',
    nom: 'Console Sahel en marbre',
    categorie: 'consoles-et-miroirs',
    prix: 94000,
    nbImages: 2,
    description: 'Plateau en marbre sur piètement en métal doré. Une pièce d\'entrée, pas un meuble de rangement.',
    dimensions: { largeur: 120, profondeur: 38, hauteur: 82 },
    materiaux: ['Marbre', 'Métal'],
    couleurs: c('blancCasse'),
    disponibilite: 'SUR_COMMANDE',
    delaiLivraison: '3 à 4 semaines',
  },

  // ── Salon de Jardin ────────────────────────────────────────────────────────
  {
    ref: 'PALMA',
    nom: 'Salon de jardin Palma',
    categorie: 'salon-de-jardin',
    prix: 186000,
    nbImages: 3,
    description:
      "Canapé deux places, deux fauteuils et une table basse en résine tressée sur structure aluminium. Coussins déhoussables en tissu traité anti-UV.",
    dimensions: { largeur: 160, profondeur: 75, hauteur: 70 },
    materiaux: ['Résine tressée', 'Aluminium', 'Tissu'],
    couleurs: c('grisPerle', 'beigeSable'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
    isFeatured: true,
  },
  {
    ref: 'IBIZA',
    nom: 'Ensemble repas jardin Ibiza',
    categorie: 'salon-de-jardin',
    prix: 142000,
    nbImages: 2,
    description: 'Table six places et six chaises empilables en aluminium. Plateau en verre trempé.',
    dimensions: { largeur: 180, profondeur: 90, hauteur: 75 },
    materiaux: ['Aluminium', 'Verre trempé', 'Résine tressée'],
    couleurs: c('anthracite', 'beigeSable'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
  },
  {
    ref: 'SIDI FREDJ',
    nom: 'Bain de soleil Sidi Fredj',
    categorie: 'salon-de-jardin',
    prix: 86000,
    nbImages: 2,
    description: 'Dossier inclinable sur cinq positions, roulettes à l\'arrière. Vendu par deux.',
    dimensions: { largeur: 200, profondeur: 70, hauteur: 35 },
    materiaux: ['Résine tressée', 'Aluminium', 'Tissu'],
    couleurs: c('grisPerle', 'creme'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '5 à 8 jours',
  },
  {
    ref: 'ZERALDA',
    nom: 'Salon de jardin Zeralda',
    categorie: 'salon-de-jardin',
    prix: 224000,
    nbImages: 3,
    description:
      "Angle huit places avec table basse, en résine tressée sur structure aluminium. Modulable : les éléments se séparent.",
    dimensions: { largeur: 300, profondeur: 210, hauteur: 68 },
    materiaux: ['Résine tressée', 'Aluminium', 'Tissu'],
    couleurs: c('anthracite', 'beigeSable'),
    disponibilite: 'SUR_COMMANDE',
    delaiLivraison: '2 à 3 semaines',
  },

  // ── Décoration ─────────────────────────────────────────────────────────────
  {
    ref: 'ATLAS 200',
    nom: 'Tapis Atlas 200x290',
    categorie: 'decoration',
    prix: 48000,
    nbImages: 2,
    description: 'Tapis à poils courts, motif géométrique discret. Dos antidérapant. Se nettoie à sec.',
    dimensions: { largeur: 200, profondeur: 290, hauteur: 1 },
    materiaux: ['Polypropylène'],
    couleurs: c('beigeSable', 'grisPerle', 'vertOlive'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'SOLEIL',
    nom: 'Suspension Soleil',
    categorie: 'decoration',
    prix: 22000,
    nbImages: 2,
    description: 'Suspension en rotin tressé, diamètre 50 cm. Douille E27, ampoule non fournie.',
    dimensions: { largeur: 50, profondeur: 50, hauteur: 40 },
    materiaux: ['Rotin', 'Métal'],
    couleurs: c('chene'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
    isNouveau: true,
  },
  {
    ref: 'DJEMILA',
    nom: 'Lampadaire Djemila',
    categorie: 'decoration',
    prix: 32000,
    nbImages: 2,
    description: 'Lampadaire à arc, abat-jour en tissu et base en marbre. Interrupteur au pied.',
    dimensions: { largeur: 55, profondeur: 30, hauteur: 165 },
    materiaux: ['Métal', 'Marbre', 'Tissu'],
    couleurs: c('anthracite', 'creme'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'TASSILI',
    nom: 'Vase Tassili, lot de trois',
    categorie: 'decoration',
    prix: 15500,
    nbImages: 1,
    description: 'Trois vases en céramique émaillée de hauteurs différentes. Finition mate.',
    dimensions: { largeur: 18, profondeur: 18, hauteur: 35 },
    materiaux: ['Céramique'],
    couleurs: c('creme', 'terracotta', 'vertOlive'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'KABYLIE',
    nom: 'Tapis Kabylie 160x230',
    categorie: 'decoration',
    prix: 36000,
    nbImages: 2,
    description: 'Tissage plat à motif berbère, laine mélangée. Réversible.',
    dimensions: { largeur: 160, profondeur: 230, hauteur: 1 },
    materiaux: ['Laine mélangée'],
    couleurs: c('creme', 'anthracite'),
    disponibilite: 'EN_STOCK',
    delaiLivraison: '3 à 5 jours',
  },
  {
    ref: 'MIROIR SOLEIL',
    nom: 'Miroir soleil décoratif',
    categorie: 'decoration',
    prix: 18500,
    nbImages: 1,
    description: 'Miroir décoratif à rayons en métal, diamètre total 80 cm. Se pose au-dessus d\'une console.',
    dimensions: { largeur: 80, profondeur: 4, hauteur: 80 },
    materiaux: ['Métal', 'Verre'],
    couleurs: c('chene', 'anthracite'),
    disponibilite: 'RUPTURE',
    delaiLivraison: '3 à 5 jours',
  },
];

export default { CATEGORIES, PRODUITS };
